// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCUQlC8VeqtuLQ-bCyaFajOWNAxeO56Rc',
    appId: '1:606234349671:web:1ad900671eb06d2eb244c2',
    messagingSenderId: '606234349671',
    projectId: 'qattama-web-app',
    authDomain: 'qattama-web-app.firebaseapp.com',
    storageBucket: 'qattama-web-app.appspot.com',
    measurementId: 'G-QSGLWKCDFR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKofg46B7W5RQO4k3dPtTFcRX7qrBHh3o',
    appId: '1:606234349671:android:ca616136e0df8b34b244c2',
    messagingSenderId: '606234349671',
    projectId: 'qattama-web-app',
    storageBucket: 'qattama-web-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq7yHOtU2-RdHaIjQxaxVpmF2ceceoHgM',
    appId: '1:606234349671:ios:c3824a690e2a7f53b244c2',
    messagingSenderId: '606234349671',
    projectId: 'qattama-web-app',
    storageBucket: 'qattama-web-app.appspot.com',
    iosBundleId: 'com.example.qattamaWebApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDq7yHOtU2-RdHaIjQxaxVpmF2ceceoHgM',
    appId: '1:606234349671:ios:c3824a690e2a7f53b244c2',
    messagingSenderId: '606234349671',
    projectId: 'qattama-web-app',
    storageBucket: 'qattama-web-app.appspot.com',
    iosBundleId: 'com.example.qattamaWebApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCUQlC8VeqtuLQ-bCyaFajOWNAxeO56Rc',
    appId: '1:606234349671:web:bcaae3160366b62ab244c2',
    messagingSenderId: '606234349671',
    projectId: 'qattama-web-app',
    authDomain: 'qattama-web-app.firebaseapp.com',
    storageBucket: 'qattama-web-app.appspot.com',
    measurementId: 'G-ZDKYYK96GB',
  );
}
